### ISSUE TITLE
Improve roadmap visibility; add GitHub guide [Community meeting 2023-09]

### ISSUE THREAD

**Issue by Zack-83** [rdmorganiser/rdmorganiser.github.io#48]
- [ ] Roadmap apparent on the RDMO homepage, not under guide for admins ("marketing") --> #62 
 - [ ] GitHub-Handbook for new users: "how to use GitHub", "how to create an issue"
 - [ ] Not all details in website: link to release notes / "What's new"
